"""Initial schema: dealerships, vehicles and vehicle actions.

Written from an autogenerated draft, then corrected by hand:
- Alembic does not generate expression indexes, so the case-insensitive
  make/model index was added here.
- The draft created the action_type check constraint twice; the duplicate was removed.

Revision ID: 0001
Revises:
Create Date: 2026-09-27
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

ACTION_TYPES = (
    "PRICE_REDUCTION_PLANNED",
    "MARKETING_PROMOTION",
    "TRANSFER_TO_ANOTHER_DEALERSHIP",
    "SEND_TO_AUCTION",
    "UNDER_REVIEW",
    "OTHER",
)


def upgrade() -> None:
    op.create_table(
        "dealership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=False),
        sa.Column("dealership_id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("model_year", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("stock_in_date", sa.Date(), nullable=True),
        sa.Column("sold_date", sa.Date(), nullable=True),
        sa.CheckConstraint("price >= 0", name="ck_vehicle_price_not_negative"),
        sa.CheckConstraint(
            "sold_date IS NULL OR stock_in_date IS NULL OR sold_date >= stock_in_date",
            name="ck_vehicle_sold_after_stock_in",
        ),
        sa.ForeignKeyConstraint(["dealership_id"], ["dealership.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vehicle_dealership_sold_stock_in",
        "vehicle",
        ["dealership_id", "sold_date", "stock_in_date"],
    )
    op.create_index("ix_vehicle_stock_in_date", "vehicle", ["stock_in_date"])
    op.create_index(
        "ix_vehicle_make_model_lower",
        "vehicle",
        [sa.text("lower(make)"), sa.text("lower(model)")],
    )
    op.create_index("ix_vehicle_vin", "vehicle", ["vin"])

    op.create_table(
        "vehicle_action",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                *ACTION_TYPES,
                name="action_type",
                native_enum=False,
                create_constraint=True,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vehicle_action_vehicle_created", "vehicle_action", ["vehicle_id", "created_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_vehicle_action_vehicle_created", table_name="vehicle_action")
    op.drop_table("vehicle_action")
    op.drop_index("ix_vehicle_vin", table_name="vehicle")
    op.drop_index("ix_vehicle_make_model_lower", table_name="vehicle")
    op.drop_index("ix_vehicle_stock_in_date", table_name="vehicle")
    op.drop_index("ix_vehicle_dealership_sold_stock_in", table_name="vehicle")
    op.drop_table("vehicle")
    op.drop_table("dealership")
